name: Pull Request
run-name: ${{ github.event.pull_request.title }} pull request run 🚀
on:
  workflow_dispatch:
    inputs: 
      target:
        description: 'Build target for dependencies'
        required: true
        default: 'x64'
      config:
        description: 'Build configuration'
        required: false
        default: 'RelWithDebInfo'
      package:
        description: 'Create Windows or macOS installation package'
        required: false
        default: 'true'  # Set to true to trigger the condition
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [master, main, pipeline-pr, pipeline-test]
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  check-format:
    name: Check Formatting 🔍
    uses: ./.github/workflows/check-format.yaml
    permissions:
      contents: read

  build-project:
    name: Build Project 🧱
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
    permissions:
      contents: read
